### ISSUE TITLE
Problem with displaying events in the "Month" section

### ISSUE THREAD

**Issue by leirbag95** [kvyatkovskys/KVKCalendar#24] opened 2019-12-02 14:47 UTC
There is a problem when you want to display several events with different months.
For example, if I create one event on December 20 and another on November 20, in the "Month" section when I scroll around November, it is the first event created that will be displayed, namely the event of December 20.
The date is well referenced but not the rest....
![Capture d’écran 2019-12-02 à 15 46 43](https://user-images.githubusercontent.com/17054452/69968563-f27f8d80-151a-11ea-9e1d-4f26bfbe891a.png)
![Capture d’écran 2019-12-02 à 15 46 38](https://user-images.githubusercontent.com/17054452/69968578-f8756e80-151a-11ea-803e-c2e8e38e9fe1.png)

**Comment by kvyatkovskys** [comment] 2019-12-02 17:32
Hello Gabriel )
I'll take a look the bug as soon as possible.

**Comment by leirbag95** [comment] 2019-12-03 10:46
Ok thank you very much!!
In case you haven't understood the bug which happened, don't hesitate to tell me and I'll give you another example ;-)

**Comment by kvyatkovskys** [comment] 2019-12-07 18:38
I couldn't reproduced the issue. Can you write more information about this.

**Comment by leirbag95** [comment] 2019-12-09 08:35
For instance, in your example change the "New 3" event (try something like the following pic.)
Scroll to this date (so here 2018-11-01) and you'll see that the event, which is normally the "New 3" event was replace by the first event in your  `events.json` (here "Event Number 1")

**The date is well met but not the content**


![Capture d’écran 2019-12-09 à 09 30 35](https://user-images.githubusercontent.com/17054452/70420046-0ff6af00-1a67-11ea-81b3-8a4357fe928b.png)
![Capture d’écran 2019-12-09 à 09 34 21](https://user-images.githubusercontent.com/17054452/70420059-1a18ad80-1a67-11ea-9ff5-b79b70370607.png)
![Capture d’écran 2019-12-09 à 09 34 27](https://user-images.githubusercontent.com/17054452/70420065-1b49da80-1a67-11ea-9d77-ce568a4ae59c.png)

**Comment by kvyatkovskys** [comment] 2019-12-22 11:54
Yep, I can reproduce. Bug will be fixed in next release version 0.2.2 (soon)
Thx)

**Comment by kvyatkovskys** [comment] 2019-12-24 09:31
fixed in v0.2.2

**Closed as completed by kvyatkovskys** 2019-12-24 09:31 UTC
Labels: bug
